name: C/C++ CI

env:
  BUILD_CONFIGURATION: Release
  SOLUTION_FILE_PATH: Engine/ThirdParty/glew/build
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      shell: bash
      run: sudo apt-get install x11-xserver-utils libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gcc make g++ libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev

    - name: Checkout submodules
      shell: bash
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Compile GLEW
      shell: bash
      run: cd Engine/ThirdParty/glew/auto && make && cd ../ && make && cd ../../../ && ls
    - name: Create project
      shell: bash
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git 
    - name: Extract project
      run: cp UVKSampleProject/*.* . -r && cp UVKSampleProject/*/ . -r
    - name: Generated generated files
      shell: bash
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && ./UVKBuildTool
    - name: Make build directory and cmake
      shell: bash
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && make
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    #- name: Fix GLEW errors
    #  run: del Engine/ThirdParty/glew/config/Makefile.mingw && copy Helpful/Makefile.mingw Engine/ThirdParty/glew/config/
    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1
    - name: Restore NuGet packages
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: nuget restore ${{env.SOLUTION_FILE_PATH}}
    - name: Build
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}}
    #- name: Compile GLEW
    #  run: cd Engine/ThirdParty/glew/build && msbuild glew.sln /Build Release 
    - name: Create project
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git 
    - name: Extract project
      run: robocopy UVKSampleProject/ .
    - name: Generated generated files
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && mingw32-make && UVKBuildTool
    - name: Make build directory and cmake
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && mingw32-make
