name: C/C++ CI

env:
  BUILD_CONFIGURATION: Release
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      shell: bash
      run: sudo apt-get install x11-xserver-utils libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gcc make g++ libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev libvulkan1 mesa-vulkan-drivers vulkan-utils && wget -qO - https://packages.lunarg.com/lunarg-signing-key-pub.asc | sudo apt-key add - && sudo wget -qO /etc/apt/sources.list.d/lunarg-vulkan-1.2.162-focal.list https://packages.lunarg.com/vulkan/1.2.162/lunarg-vulkan-1.2.162-focal.list && sudo apt update && sudo apt install vulkan-sdk

    - name: Checkout submodules
      shell: bash
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Compile GLEW
      shell: bash
      run: cd Engine/ThirdParty/glew/auto && make && cd ../ && make && cd ../../../ && ls
    - name: Create project
      shell: bash
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git 
    - name: Extract project
      run: cp UVKSampleProject/*.* . -r && cp UVKSampleProject/*/ . -r
    - name: Generated generated files
      shell: bash
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && ./UVKBuildTool --generate
    - name: Make build directory and cmake
      shell: bash
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && alias g++='g++ -lstdc++fs' && alias gcc='gcc -lstdc++fs' && make && ./Game
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Compile GLEW
      run: cd Engine/ThirdParty/glew/auto/ && mingw32-make && cd ../ && mingw32-make install && cd ../../../ && dir
    - name: Create project
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git && dir
    - name: Extract project
      run: xcopy /i /e /c /k /y /r UVKSampleProject .  
    - name: Generated generated files
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && mingw32-make && dir && ./UVKBuildTool.exe --generate
    - name: Make build directory and cmake
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && mingw32-make && ./Game
  MacOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      shell: bash
      run: brew install glew && brew install glfw
    - name: Checkout submodules
      shell: bash
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Compile GLEW
      shell: bash
      run: cd Engine/ThirdParty/glew/auto && make && cd ../ && make && cd ../../../ && ls
    - name: Create project
      shell: bash
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git 
    - name: Extract project
      run: mv UVKSampleProject/*.* . 
    - name: Generated generated files
      shell: bash
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && ./UVKBuildTool --generate
    - name: Make build directory and cmake
      shell: bash
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && make && ./Game
