name: C/C++ CI

env:
  BUILD_CONFIGURATION: Release
  #SOLUTION_FILE_PATH: Engine/ThirdParty/glew/build/vc15/glew_shared.vcxproj
  #SOLUTION_FILE_PATH2: Engine/ThirdParty/glew/build/vc15/glew_static.vcxproj
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Get dependencies
      shell: bash
      run: sudo apt-get install x11-xserver-utils libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev gcc make g++ libxmu-dev libxi-dev libgl-dev libglu1-mesa-dev

    - name: Checkout submodules
      shell: bash
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    - name: Compile GLEW
      shell: bash
      run: cd Engine/ThirdParty/glew/auto && make && cd ../ && make && cd ../../../ && ls
    - name: Create project
      shell: bash
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git 
    - name: Extract project
      run: cp UVKSampleProject/*.* . -r && cp UVKSampleProject/*/ . -r
    - name: Generated generated files
      shell: bash
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && make && ./UVKBuildTool
    - name: Make build directory and cmake
      shell: bash
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && make
  Windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
          git submodule sync --recursive
          git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1
    #- name: Configure dependencies
    #  run: | 
    #    Invoke-WebRequest -Method Get -Uri https://go.microsoft.com/fwlink/p/?LinkId=323507 -OutFile sdksetup.exe -UseBasicParsing
    #    Start-Process -Wait sdksetup.exe -ArgumentList "/q", "/norestart", "/features", "OptionId.WindowsDesktopSoftwareDevelopmentKit", "OptionId.NetFxSoftwareDevelopmentKit"
    #- name: Fix GLEW errors
    #  run: del Engine/ThirdParty/glew/config/Makefile.mingw && copy Helpful/Makefile.mingw Engine/ThirdParty/glew/config/
    #- name: Add MSBuild to PATH
    #  uses: microsoft/setup-msbuild@v1
    #- name: Restore NuGet packages
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: dir Engine/ThirdParty/glew/build && nuget restore ${{env.SOLUTION_FILE_PATH}} && nuget restore ${{env.SOLUTION_FILE_PATH2}}
    #- name: Build GLEW
    #  working-directory: ${{env.GITHUB_WORKSPACE}}
    #  run: msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH}} && msbuild /m /p:Configuration=${{env.BUILD_CONFIGURATION}} ${{env.SOLUTION_FILE_PATH2}}
    - name: Compile GLEW
      run: cd Engine/ThirdParty/glew/auto/ && mingw32-make && cd ../ && mingw32-make install && cd ../../../ && dir
    - name: Create project
      run: git clone https://github.com/MadLadSquad/UVKSampleProject.git && dir
    - name: Extract project
      run: xcopy /i /e /c /k /y /r UVKSampleProject .  
    - name: Generated generated files
      run: cd UVKBuildTool/ && mkdir build && cd build && cmake -G "Unix Makefiles" .. && mingw32-make && dir && UVKBuildTool.exe
    - name: Make build directory and cmake
      run: ls && mkdir build && cd build && cmake .. -G "Unix Makefiles" && mingw32-make
