name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Hello and welcome to the UntitledVulkanGameEngine. Our automation bots discovered this is your first issue, thank you for helping make our engine better and growing the community! Me or the other maintainers are going to visit this issue soon. - Madman10K'
        pr-message: 'Hello and welcome to the UntitledVulkanGameEngine. Our automation bots discovered this is your first pull request, thank you for helping make our engine better and growing the community! Me or the other maintainers are going to visit this PR soon. - Madman10K'
